[package]
authors = ["Vince Vasta <vince.vasta@gmail.com>"]
description = "A command line data manipulation tool inspired by the dplyr grammar."
repository = "https://github.com/vincev/dply-rs"
edition = "2021"
license = "Apache-2.0"
name = "dply"
version = "0.1.9"
rust-version = "1.70.0"

[dependencies]
anyhow = "1.0"
clap = { version = "4.2", features = ["derive"] }
comfy-table = "6"
datafusion = { version = "26", default-features = false }
home = "0.5"
lru = "0.10.0"
nom = "7"
reedline = "0.20"
thiserror = "1.0"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "sync"] }

[dev-dependencies]
indoc = "2"
